platform :ios, '10.0'
source 'https://github.com/CocoaPods/Specs.git'
target 'swiftTemplate' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for swiftTemplate
pod 'Moya', '~> 13.0.1'
pod 'ObjectMapper', '~> 3.5.2'
pod 'AlamofireImage', '~> 3.5.2'
pod 'SwiftyBeaver', '~> 1.7.0'
pod 'IQKeyboardManagerSwift', '~> 6.4.0'
pod 'MJRefresh', '~> 3.2.0'

end
