platform :ios, '16.0'
source 'https://github.com/CocoaPods/Specs.git'
target 'swiftTemplate' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for swiftTemplate
  pod 'AMapLocation','~> 2.6.5'
  pod 'AMapSearch','~> 7.3.0'
  pod 'AMap3DMap','~> 7.4.0'
  pod 'Moya', '~> 13.0.1'
  pod 'ObjectMapper', '~> 3.5.2'
  pod 'SwiftyBeaver', '~> 1.7.0'
  pod 'IQKeyboardManagerSwift', '~> 6.4.0'
  pod 'MJRefresh', '~> 3.2.0'
  pod 'Gifu', '~> 3.2.0'
  pod 'SwiftyRSA','~>1.5.0'
  pod 'CryptoSwift' , '~> 1.3.8'
  pod 'Bugly','~> 2.5.0'
  pod 'FSPagerView','~> 0.8.3'
  pod 'Kingfisher', '~> 5.14.0'
  pod 'YPImagePicker' ,'~> 4.2.1'
  pod 'InputBarAccessoryView' , '~> 4.3.2'
  pod 'AliyunOSSiOS' , '~> 2.10.8'
  pod 'TXIMSDK_iOS'
  # 防止 TUI 组件里的 *.xcassets 与您项目里面冲突。
  #install! 'cocoapods', :disable_input_output_paths => true

  # TUI 组件依赖了静态库，需要屏蔽如下设置，如果报错，请参考常见问题说明。
  # use_frameworks!

  # 集成聊天功能
  pod 'TUIChat'
  # 集成会话功能
  pod 'TUIConversation'
end
